export interface College {
  id: string;
  name: string;
  location: string;
  state: string;
  fees: number;
  rating: number;
  coursesOffered: string[];
  placementPercentage: number;
  averagePackage: number;
  rank: number;
  reviews: number;
  description: string;
  founded: number;
  studentCount: number;
  acceptanceRate: number;
  image: string;
}

export const mockColleges: College[] = [
  {
    id: "1",
    name: "Amrita Vishwa Vidyapeetham",
    location: "Coimbatore",
    state: "Tamil Nadu",
    fees: 450000,
    rating: 4.5,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "EEE"],
    placementPercentage: 94,
    averagePackage: 820000,
    rank: 4,
    reviews: 2345,
    description: "Premier private institution offering world-class education with modern infrastructure",
    founded: 1956,
    studentCount: 18000,
    acceptanceRate: 35,
    image: "https://www.diginerve.com/blogs/wp-content/uploads/2023/06/Amrita-Vishwa-Vidyapeetham-Courses-Admission-Process-_-Fee-Structure.webp",
  },
  {
    id: "2",
    name: "Birla Institute of Technology and Science",
    location: "Pilani",
    state: "Rajasthan",
    fees: 550000,
    rating: 4.7,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "Chemical"],
    placementPercentage: 96,
    averagePackage: 1200000,
    rank: 2,
    reviews: 3456,
    description: "Globally recognized institution with excellent industry connections",
    founded: 1964,
    studentCount: 10000,
    acceptanceRate: 28,
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/c0/7e/7e/birla-institute-of-technology.jpg?w=1200&h=-1&s=1",
  },
  {
    id: "3",
    name: "BML Munjal University",
    location: "Gurugram",
    state: "Haryana",
    fees: 380000,
    rating: 4.2,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Biotechnology"],
    placementPercentage: 89,
    averagePackage: 650000,
    rank: 8,
    reviews: 1234,
    description: "Modern university with focus on industry-ready education",
    founded: 2014,
    studentCount: 3500,
    acceptanceRate: 45,
    image: "https://www.guidanceforever.org/wp-content/uploads/2023/11/bml-munjal-university-gurgaon-featured.jpg",
  },
  {
    id: "4",
    name: "Chennai Institute of Technology",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 320000,
    rating: 4.1,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 85,
    averagePackage: 580000,
    rank: 12,
    reviews: 891,
    description: "Known for strong technical education and good placement record",
    founded: 2010,
    studentCount: 5000,
    acceptanceRate: 52,
    image: "https://content.jdmagicbox.com/v2/comp/chennai/f5/044pxx44.xx44.100723135332.f5f5/catalogue/chennai-institute-of-technology-kundrathur-chennai-colleges-2erv27k.jpg",
  },
  {
    id: "5",
    name: "Dayananda Sagar Academy of Technology",
    location: "Bangalore",
    state: "Karnataka",
    fees: 380000,
    rating: 4.3,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "EEE"],
    placementPercentage: 91,
    averagePackage: 720000,
    rank: 6,
    reviews: 1567,
    description: "Excellence in engineering education with modern campus facilities",
    founded: 1995,
    studentCount: 8000,
    acceptanceRate: 40,
    image: "https://static.boostmytalent.com/img/univ/dayanand-sagar-academy-of-technology-management-dastm-bangalore-campus.webp",
  },
  {
    id: "6",
    name: "Delhi Technological University",
    location: "Delhi",
    state: "Delhi",
    fees: 180000,
    rating: 4.4,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "EEE"],
    placementPercentage: 92,
    averagePackage: 850000,
    rank: 3,
    reviews: 2789,
    description: "Government institution with excellent academic standards",
    founded: 1941,
    studentCount: 7500,
    acceptanceRate: 15,
    image: "https://learn.vcnow.in/wp-content/uploads/2026/01/DTU.jpg",
  },
  {
    id: "7",
    name: "Easwari Engineering College",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 300000,
    rating: 4.0,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 82,
    averagePackage: 520000,
    rank: 15,
    reviews: 745,
    description: "Good college with focus on practical engineering education",
    founded: 1996,
    studentCount: 4200,
    acceptanceRate: 58,
    image: "https://srmeaswari.ac.in/wp-content/uploads/2026/02/srm-easwari-image-1024x384.webp",
  },
  {
    id: "8",
    name: "Frankfinn Institute of Air Hostess Training",
    location: "Mumbai",
    state: "Maharashtra",
    fees: 200000,
    rating: 3.8,
    coursesOffered: ["Air Hostess", "Ground Staff", "Cabin Crew"],
    placementPercentage: 88,
    averagePackage: 380000,
    rank: 18,
    reviews: 523,
    description: "Specialized training institute for aviation industry professionals",
    founded: 2003,
    studentCount: 2000,
    acceptanceRate: 65,
    image: "https://www.frankfinn.com/img/fly-hight19.11.webp",
  },
  {
    id: "9",
    name: "Gautam Buddha University",
    location: "Noida",
    state: "Uttar Pradesh",
    fees: 280000,
    rating: 4.0,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 84,
    averagePackage: 600000,
    rank: 14,
    reviews: 634,
    description: "Affordable private university with good academic programs",
    founded: 2006,
    studentCount: 6000,
    acceptanceRate: 50,
    image: "https://campuspro.co.in/collage-image/1749039179_row_27.jpg",
  },
  {
    id: "10",
    name: "GLA University",
    location: "Mathura",
    state: "Uttar Pradesh",
    fees: 320000,
    rating: 4.1,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 86,
    averagePackage: 640000,
    rank: 11,
    reviews: 789,
    description: "Quality education with good infrastructure and industry tie-ups",
    founded: 1992,
    studentCount: 5500,
    acceptanceRate: 48,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwFM4-yTxz0JGNFpz8ll5OB5V3Ganq6gVcCg&s",
  },
  {
    id: "11",
    name: "Hindustan Institute of Technology",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 350000,
    rating: 4.2,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 88,
    averagePackage: 700000,
    rank: 9,
    reviews: 1123,
    description: "Well-established institution with strong alumni network",
    founded: 1999,
    studentCount: 6500,
    acceptanceRate: 46,
    image: "https://images.shiksha.com/mediadata/images/1591098778phptfXYDI.jpeg",
  },
  {
    id: "12",
    name: "Hindustan University",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 360000,
    rating: 4.3,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "Biomedical"],
    placementPercentage: 90,
    averagePackage: 760000,
    rank: 7,
    reviews: 1456,
    description: "Comprehensive university with diverse course offerings",
    founded: 1995,
    studentCount: 7000,
    acceptanceRate: 44,
    image: "https://content.jdmagicbox.com/v2/comp/mumbai/t4/022pxx22.xx22.150131130904.f4t4/catalogue/hindustan-university-vile-parle-east-mumbai-pharmacy-institutes-oof0k0ter4.jpg",
  },
  {
    id: "13",
    name: "IIT Bombay",
    location: "Mumbai",
    state: "Maharashtra",
    fees: 250000,
    rating: 4.9,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "EEE", "Chemical"],
    placementPercentage: 99,
    averagePackage: 1800000,
    rank: 1,
    reviews: 5678,
    description: "India&apos;s premier engineering institution with world-class faculty",
    founded: 1958,
    studentCount: 9000,
    acceptanceRate: 5,
    image: "https://c.ndtvimg.com/2025-07/nskbnsmg_iit-bombay-_625x300_21_July_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738",
  },
  {
    id: "14",
    name: "IIT Delhi",
    location: "Delhi",
    state: "Delhi",
    fees: 250000,
    rating: 4.8,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "EEE"],
    placementPercentage: 98,
    averagePackage: 1650000,
    rank: 2,
    reviews: 4567,
    description: "Top-tier institution with excellent research opportunities",
    founded: 1961,
    studentCount: 8500,
    acceptanceRate: 6,
    image: "https://home.iitd.ac.in/images/for-faculty/camp8.jpg",
  },
  {
    id: "15",
    name: "IIT Guwahati",
    location: "Guwahati",
    state: "Assam",
    fees: 250000,
    rating: 4.7,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 97,
    averagePackage: 1400000,
    rank: 4,
    reviews: 3234,
    description: "Leading IIT with strong placement and academic excellence",
    founded: 1994,
    studentCount: 6000,
    acceptanceRate: 7,
    image: "https://images.shiksha.com/mediadata/images/articles/1619666185phpMo6mWX.jpeg",
  },
  {
    id: "16",
    name: "IIT Kharagpur",
    location: "Kharagpur",
    state: "West Bengal",
    fees: 250000,
    rating: 4.8,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "EEE"],
    placementPercentage: 99,
    averagePackage: 1700000,
    rank: 2,
    reviews: 4234,
    description: "Historic IIT with strong technical education and industry partnerships",
    founded: 1951,
    studentCount: 9500,
    acceptanceRate: 6,
    image: "https://m.economictimes.com/thumb/msid-124785088,width-1600,height-900,resizemode-4,imgsize-159884/iit-kharagpur-to-introduce-alternative-admission-routes-for-btech-and-bs-courses.jpg",
  },
  {
    id: "17",
    name: "IIT Madras",
    location: "Chennai",
    state: "Tamil Nadu",
    fees: 250000,
    rating: 4.8,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "EEE"],
    placementPercentage: 99,
    averagePackage: 1750000,
    rank: 2,
    reviews: 4123,
    description: "Excellence in engineering with state-of-the-art facilities",
    founded: 1959,
    studentCount: 8000,
    acceptanceRate: 6,
    image: "https://scispace.com/resources/content/images/2021/07/IITM-Indian-Institute-of-Technology-Madras.jpeg",
  },
  {
    id: "18",
    name: "IIT Roorkee",
    location: "Roorkee",
    state: "Uttarakhand",
    fees: 250000,
    rating: 4.7,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "EEE"],
    placementPercentage: 97,
    averagePackage: 1350000,
    rank: 5,
    reviews: 3567,
    description: "Historic institution with excellent placement record",
    founded: 1853,
    studentCount: 7500,
    acceptanceRate: 7,
    image: "https://images.shiksha.com/mediadata/images/articles/1657090944php02IDCv.jpeg",
  },
  {
    id: "19",
    name: "Jaipur National University",
    location: "Jaipur",
    state: "Rajasthan",
    fees: 250000,
    rating: 3.9,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 80,
    averagePackage: 480000,
    rank: 19,
    reviews: 456,
    description: "Growing university with focus on practical learning",
    founded: 2005,
    studentCount: 4500,
    acceptanceRate: 60,
    image: "https://www.jnujaipur.ac.in/public/uploads/image/522imguf_career.webp",
  },
  {
    id: "20",
    name: "JSS Academy of Technical Education",
    location: "Bangalore",
    state: "Karnataka",
    fees: 320000,
    rating: 4.0,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 83,
    averagePackage: 550000,
    rank: 16,
    reviews: 612,
    description: "Quality technical education with good placement assistance",
    founded: 2000,
    studentCount: 4800,
    acceptanceRate: 55,
    image: "https://www.jssaten.ac.in/assets/a6.jpg",
  },
  {
    id: "21",
    name: "K.Ramakrishnan College of Engineering",
    location: "Tamil Nadu",
    state: "Tamil Nadu",
    fees: 290000,
    rating: 3.9,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 81,
    averagePackage: 510000,
    rank: 17,
    reviews: 534,
    description: "Affordable engineering college with good faculty",
    founded: 2010,
    studentCount: 3800,
    acceptanceRate: 62,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvcdflUifa_CwciEzQ9-96GuY9bMXu3xB8wg&s",
  },
  {
    id: "22",
    name: "Kalasalingam Academy of Research and Education",
    location: "Virudunagar",
    state: "Tamil Nadu",
    fees: 280000,
    rating: 4.0,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 84,
    averagePackage: 590000,
    rank: 13,
    reviews: 678,
    description: "Reputed institution with strong academia and placements",
    founded: 1984,
    studentCount: 5200,
    acceptanceRate: 51,
    image: "https://www.kalasalingam.ac.in/wp-content/uploads/2021/06/IMG_1066-1-scaled.jpg",
  },
  {
    id: "23",
    name: "KL Deemed to be University",
    location: "Vijayawada",
    state: "Andhra Pradesh",
    fees: 300000,
    rating: 4.1,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 87,
    averagePackage: 670000,
    rank: 10,
    reviews: 923,
    description: "Quality university with focus on student development",
    founded: 1997,
    studentCount: 6800,
    acceptanceRate: 49,
    image: "https://timess3spore.s3.amazonaws.com/ndata/media/Counsellor/CollegeImage/2023/04/03/1680509712.jpg",
  },
  {
    id: "24",
    name: "Lloyd Institute of Engineering and Technology",
    location: "Noida",
    state: "Uttar Pradesh",
    fees: 310000,
    rating: 3.8,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 79,
    averagePackage: 470000,
    rank: 20,
    reviews: 389,
    description: "Emerging institution with decent infrastructure",
    founded: 2009,
    studentCount: 3200,
    acceptanceRate: 68,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJDO4tzJ9iHgh1sW4ApG0Ge2ANppHerJb4Og&s",
  },
  {
    id: "25",
    name: "Lovely Professional University",
    location: "Jalandhar",
    state: "Punjab",
    fees: 340000,
    rating: 4.2,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "EEE"],
    placementPercentage: 89,
    averagePackage: 710000,
    rank: 9,
    reviews: 1289,
    description: "Large private university with diverse programs",
    founded: 2005,
    studentCount: 22000,
    acceptanceRate: 42,
    image: "https://api.salahlo.in/media/university/photos/online-lovely-professional-university-banner.webp",
  },
  {
    id: "26",
    name: "Manipal Institute of Technology",
    location: "Manipal",
    state: "Karnataka",
    fees: 480000,
    rating: 4.6,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "Chemical"],
    placementPercentage: 95,
    averagePackage: 1100000,
    rank: 3,
    reviews: 2856,
    description: "Prestigious institution with excellent campus and placements",
    founded: 1953,
    studentCount: 11000,
    acceptanceRate: 22,
    image: "https://www.manipal.edu/content/dam/manipal/mu/imagesnew/Campuslife/1440%20x%20800px%20.jpg",
  },
  {
    id: "27",
    name: "Mody University of Science and Technology",
    location: "Rajasthan",
    state: "Rajasthan",
    fees: 270000,
    rating: 3.9,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 80,
    averagePackage: 500000,
    rank: 18,
    reviews: 478,
    description: "Affordable private university with good academics",
    founded: 2005,
    studentCount: 4000,
    acceptanceRate: 59,
    image: "https://images.shiksha.com/mediadata/images/1743153132phpYDtP8y.jpeg",
  },
  {
    id: "28",
    name: "Nirma University",
    location: "Ahmedabad",
    state: "Gujarat",
    fees: 380000,
    rating: 4.3,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil"],
    placementPercentage: 91,
    averagePackage: 740000,
    rank: 8,
    reviews: 1345,
    description: "Well-established institution with strong industry ties",
    founded: 1994,
    studentCount: 7200,
    acceptanceRate: 43,
    image: "https://images.indianexpress.com/2025/11/nirma_f69d69.jpg",
  },
  {
    id: "29",
    name: "NMIMS Mumbai",
    location: "Mumbai",
    state: "Maharashtra",
    fees: 520000,
    rating: 4.5,
    coursesOffered: ["CSE", "ECE", "Mechanical"],
    placementPercentage: 93,
    averagePackage: 950000,
    rank: 5,
    reviews: 2134,
    description: "Prestigious institution with international recognition",
    founded: 1981,
    studentCount: 8500,
    acceptanceRate: 32,
    image: "https://insideiim.com/_next/image?url=https%3A%2F%2Fbackend.insideiim.com%2Fwp-content%2Fuploads%2F2017%2F10%2FInside-NMIMS.jpg&w=3840&q=72",
  },
  {
    id: "30",
    name: "VIT Vellore",
    location: "Vellore",
    state: "Tamil Nadu",
    fees: 420000,
    rating: 4.5,
    coursesOffered: ["CSE", "ECE", "Mechanical", "Civil", "Chemical"],
    placementPercentage: 94,
    averagePackage: 890000,
    rank: 6,
    reviews: 2678,
    description: "Top-tier private institution with global reach",
    founded: 1984,
    studentCount: 15000,
    acceptanceRate: 26,
    image: "https://images.shiksha.com/mediadata/images/articles/1765785696phpCfpAwL.jpeg",
  },
];
